name: pull

on:
    push:
        branches: ["main"]

jobs:
    pull:
        runs-on: self-hosted
        steps:
            - name: Change directory
              run: "cd /var/www/html/web/"
            - name: Pull source
              run: "git pull"